export const types = {
  //Auth actions//
  LOGIN_START: "LOGIN_START",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAILURE",

  REGISTER_USER_START: "REGISTER_USER_START",
  REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
  REGISTER_USER_FAILURE: "REGISTER_USER_FAILURE",

  SET_AUTH: "SET_AUTH",
  //Auth Actions//

  //Listing Actions

  GET_LISTING_START: "GET_LISTING_START",
  GET_LISTING_SUCCESS: "GET_LISTING_SUCCESS",
  GET_LISTING_FAILURE: "GET_LISTING_FAILURE",

  //Listing Actions
  POST_LIST_START: "POST_LIST_START",
  POST_LIST_SUCCESS: "POST_LIST_SUCCESS",
  POST_LIST_FAILURE: "POST_LIST_FAILURE",

  // Listing Actions
  UPDATE_LISTING_START: "UPDATE_LISTING_START",
  UPDATE_LISTING_SUCCESS: "UPDATE_LISTING_SUCCESS",
  UPDATE_LISTING_FAILURE: "UPDATE_LISTING_FAILURE"
};
